version: '3'
services:
  docusaurus-tutorial:
    container_name: docusaurus-tutorial
    build:
      context: .
    ports:
      - "3000:3000"
    tty: true
#    working_dir: /opt/api/
#    command: ./node_modules/.bin/nodemon app.js
    volumes:
      - ./app:/usr/src
#    links:
#      - db
      
#  db:
#    container_name: sample_api_db 
#    image: mongo:latest 
#    ports:
#      - "27017"